version: "3.8"

services:
  kong-database:
    image: postgres:11
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    networks:
      - kong-net

  kong-migrations:
    image: kong:latest
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    command: kong migrations bootstrap
    networks:
      - kong-net

  kong:
    image: kong:latest
    container_name: kong
    depends_on:
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - kong-net

  konga:
    image: pantsel/konga:latest
    container_name: konga
    depends_on:
      - kong
    environment:
      DB_ADAPTER: "postgres"
      DB_HOST: "kong-database"
      DB_USER: "kong"
      DB_PASSWORD: "kong"
      DB_DATABASE: "kong"
    ports:
      - "1337:1337"
    networks:
      - kong-net

  edot-user-db:
    image: postgres:14
    container_name: edot-user-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: edot_user_db
    ports:
      - "5433:5432"
    volumes:
      - edot-user-db-data:/var/lib/postgresql/data
    networks:
      - kong-net

  edot-product-db:
    image: postgres:14
    container_name: edot-product-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: edot_product_db
    ports:
      - "5434:5432"
    volumes:
      - edot-product-db-data:/var/lib/postgresql/data
    networks:
      - kong-net

networks:
  kong-net:

volumes:
  kong-db-data:
  edot-user-db-data:
  edot-product-db-data:
